================================================================================
ФАЙЛ: Исходные_Казахстан.xlsx
ИЗМЕНЕНИЕ: убрать двойной ввод данных по производству
================================================================================

СУТЬ ПРОБЛЕМЫ:
  Лист "Производство_Факт" в Исходные_Казахстан.xlsx содержит те же данные,
  что и лист "Производство_Факт" в Каз_Произв_цены.xlsx.
  Пользователь вносит новые данные в оба файла вручную.

РЕШЕНИЕ:
  Запрос "Исходные" перенаправить на Каз_Произв_цены.xlsx.
  Все зависимые запросы (Производство_по_месяцам, Отгрузки_по_регионам,
  Производство_год, Отгрузки_по_кластерам) работают через "Исходные"
  и не потребуют изменений.


================================================================================
ШАГ 1. Добавить лист "Параметры" и именованную таблицу tbl_ИсхКАЗ_Параметры
        Колонки: Параметр (text), Значение (text)
================================================================================

| Параметр  | Значение                                                                          |
|-----------|-----------------------------------------------------------------------------------|
| Путь_КАЗ  | C:\projects\my-project\ОМТ\Еженедельный отчёт\Каз_Произв_цены.xlsx              |


================================================================================
ШАГ 2. Заменить запрос "Исходные"   (Connection Only)
================================================================================

БЫЛО:
    Источник = Excel.CurrentWorkbook(){[Name="Таблица1"]}[Content],
    ...

СТАЛО:

let
    Путь = Excel.CurrentWorkbook(){[Name="tbl_ИсхКАЗ_Параметры"]}[Content]{0}[Значение],
    Источник  = Excel.Workbook(File.Contents(Путь), null, true),
    Лист      = Источник{[Item="Производство_Факт", Kind="Sheet"]}[Data],
    ПовЗаг   = Table.PromoteHeaders(Лист, [PromoteAllScalars=true]),
    Типы = Table.TransformColumnTypes(ПовЗаг, {
        {"Год",          Int64.Type},
        {"Производитель", type text},
        {"Марка",        type text},
        {"янв",  type number}, {"фев",  type number}, {"мар",  type number},
        {"апр",  type number}, {"май",  type number}, {"июнь", type number},
        {"июл",  type number}, {"авг",  type number}, {"сен",  type number},
        {"окт",  type number}, {"ноя",  type number}, {"дек",  type number}
    })
in
    Типы


================================================================================
ШАГ 3. После применения -- проверить
================================================================================

1. Обновить "Исходные" → должны появиться данные из Каз_Произв_цены.xlsx
2. Обновить "Производство_по_месяцам" → данные должны совпасть с тем, что было
3. Зайти в Сборка_квартальные.xlsx → обновить "Производство_Каз" → проверить


================================================================================
ЧТО ДЕЛАТЬ С ЛИСТОМ "Производство_Факт" В ЭТОМ ФАЙЛЕ
================================================================================

После успешной проверки лист "Производство_Факт" в Исходные_Казахстан.xlsx
можно скрыть или удалить -- он больше не нужен для ввода данных.
Данные теперь живут только в Каз_Произв_цены.xlsx.

Аналогично проверить лист "Цены производителей" в Исходных_Казахстан:
  - если ни один PQ запрос его не читает (по результатам анализа -- не читает),
    лист можно скрыть. Данные по ценам идут через ЦеныКАЗ.xlsx.
