================================================================================
ФАЙЛ: Сборка_квартальные.xlsx
ПРОБЛЕМА: три бага в ИТОГ_Произв_Год, ИТОГ_Имп_Год, ИТОГ_Экс_Год
================================================================================

ПРИЧИНА 1: Самосоединение без Table.Buffer
  Джн = Table.NestedJoin(СПГ, ..., Сорт, ...)
  PQ пересчитывает правую часть лениво -- _ОбъемПГ = null везде.

ПРИЧИНА 2: Table.NestedJoin не сохраняет порядок строк.
  Сортировка до join не действует на результат.
  Итог: годы идут в произвольном порядке.

ПРИЧИНА 3: Первый год окна (2022) показывает 0% вместо "-".
  2021 за пределами фильтра, но PQ иногда даёт spurious match при expand.
  Фиксируется явной проверкой: если год = минимальный в окне → null.

ИСПРАВЛЕНИЕ:
  1. СортБуф = Table.Buffer(Сорт) -- убирает причину 1
  2. МинГодОкна = List.Min(Table.Column(СортБуф, "Год")) -- для причины 3
  3. СПГ и Джн переключить на СортБуф
  4. В формуле динамики: if [Год] = МинГодОкна → null
  5. Table.Sort в шаге Итог -- убирает причину 2


================================================================================
ЗАПРОС 1: ИТОГ_Произв_Год  (полностью)
================================================================================

// КАЗ + УЗБ | Страна | ГруппаВид | Год | Объем_Год | Объем_Период | Динамика_%
// Объем_Год: прошлые = 12 мес, тек. = до МесяцОтч
// Объем_Период: мес 1..МесяцОтч для всех лет (YoY сопоставимо)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Исх = Table.SelectRows(Производство_Отгрузки_Каз, each
        List.Contains({"Казахстан","Узбекистан"}, [Страна])
        and [Показатель] = "Производство"
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СМес = Table.AddColumn(Исх, "НомерМесяца", each Number.Mod([КлючМесяца], 100), Int64.Type),

    СГр = Table.AddColumn(СМес, "ГруппаВид", each
        if [Вид] = "ПБВ" then "ПБВ"
        else if List.Contains({"БНД","БНС","БНК"}, [Вид]) then "БН"
        else null, type text),
    Дан = Table.SelectRows(СГр, each [ГруппаВид] <> null),

    ДанГод = Table.SelectRows(Дан, each [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрГод = Table.Group(ДанГод, {"Страна","ГруппаВид","Год"},
        {{"Объем_Год", each List.Sum([Значение]), type number}}),

    ДанПер = Table.SelectRows(Дан, each [НомерМесяца] <= МесяцОтч),
    ГрПер = Table.Group(ДанПер, {"Страна","ГруппаВид","Год"},
        {{"Объем_Период", each List.Sum([Значение]), type number}}),

    Мерж = Table.ExpandTableColumn(
        Table.NestedJoin(ГрГод, {"Страна","ГруппаВид","Год"}, ГрПер, {"Страна","ГруппаВид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Мерж, {{"Страна",0},{"ГруппаВид",0},{"Год",0}}),
    СортБуф = Table.Buffer(Сорт),
    МинГодОкна = List.Min(Table.Column(СортБуф, "Год")),

    СПГ = Table.AddColumn(СортБуф, "_ГодПГ", each [Год] - 1, Int64.Type),
    Джн = Table.NestedJoin(СПГ, {"Страна","ГруппаВид","_ГодПГ"}, СортБуф, {"Страна","ГруппаВид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Расш = Table.ExpandTableColumn(Джн, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДин = Table.AddColumn(Расш, "Динамика_%", each
        let
            тек  = if [Объем_Период] = null then 0 else [Объем_Период],
            пред = [_ОбъемПГ]
        in
            if [Год] = МинГодОкна or пред = null or пред = 0 then null
            else (тек - пред) / пред, type number),

    Итог = Table.Sort(
        Table.SelectColumns(СДин, {"Страна","ГруппаВид","Год","Объем_Год","Объем_Период","Динамика_%"}),
        {{"Страна",0},{"ГруппаВид",0},{"Год",0}})
in
    Итог


================================================================================
ЗАПРОС 2: ИТОГ_Имп_Год  (полностью)
================================================================================

// Все 4 страны | Страна | ГруппаВид | Год | Объем_Год | Объем_Период | Динамика_%
// Страна = СтранаНазначения (получатель импорта)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Исх = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаНазначения])
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СГр = Table.AddColumn(
        Table.AddColumn(Исх, "Страна", each [СтранаНазначения], type text),
        "ГруппаВид", each
            if [Вид] = "ПБВ" then "ПБВ"
            else if List.Contains({"БНД","БНС","БНК"}, [Вид]) then "БН"
            else null, type text),
    Дан = Table.SelectRows(СГр, each [ГруппаВид] <> null),

    ДанГод = Table.SelectRows(Дан, each [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрГод = Table.Group(ДанГод, {"Страна","ГруппаВид","Год"},
        {{"Объем_Год", each List.Sum([Объем_тыс_т]), type number}}),

    ДанПер = Table.SelectRows(Дан, each [НомерМесяца] <= МесяцОтч),
    ГрПер = Table.Group(ДанПер, {"Страна","ГруппаВид","Год"},
        {{"Объем_Период", each List.Sum([Объем_тыс_т]), type number}}),

    Мерж = Table.ExpandTableColumn(
        Table.NestedJoin(ГрГод, {"Страна","ГруппаВид","Год"}, ГрПер, {"Страна","ГруппаВид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Мерж, {{"Страна",0},{"ГруппаВид",0},{"Год",0}}),
    СортБуф = Table.Buffer(Сорт),
    МинГодОкна = List.Min(Table.Column(СортБуф, "Год")),

    СПГ = Table.AddColumn(СортБуф, "_ГодПГ", each [Год] - 1, Int64.Type),
    Джн = Table.NestedJoin(СПГ, {"Страна","ГруппаВид","_ГодПГ"}, СортБуф, {"Страна","ГруппаВид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Расш = Table.ExpandTableColumn(Джн, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДин = Table.AddColumn(Расш, "Динамика_%", each
        let
            тек  = if [Объем_Период] = null then 0 else [Объем_Период],
            пред = [_ОбъемПГ]
        in
            if [Год] = МинГодОкна or пред = null or пред = 0 then null
            else (тек - пред) / пред, type number),

    Итог = Table.Sort(
        Table.SelectColumns(СДин, {"Страна","ГруппаВид","Год","Объем_Год","Объем_Период","Динамика_%"}),
        {{"Страна",0},{"ГруппаВид",0},{"Год",0}})
in
    Итог


================================================================================
ЗАПРОС 3: ИТОГ_Экс_Год  (полностью)
================================================================================

// Все 4 страны | Страна | ГруппаВид | Год | Объем_Год | Объем_Период | Динамика_%
// Страна = СтранаОтправления (экспортёр)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Исх = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаОтправления])
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СГр = Table.AddColumn(
        Table.AddColumn(Исх, "Страна", each [СтранаОтправления], type text),
        "ГруппаВид", each
            if [Вид] = "ПБВ" then "ПБВ"
            else if List.Contains({"БНД","БНС","БНК"}, [Вид]) then "БН"
            else null, type text),
    Дан = Table.SelectRows(СГр, each [ГруппаВид] <> null),

    ДанГод = Table.SelectRows(Дан, each [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрГод = Table.Group(ДанГод, {"Страна","ГруппаВид","Год"},
        {{"Объем_Год", each List.Sum([Объем_тыс_т]), type number}}),

    ДанПер = Table.SelectRows(Дан, each [НомерМесяца] <= МесяцОтч),
    ГрПер = Table.Group(ДанПер, {"Страна","ГруппаВид","Год"},
        {{"Объем_Период", each List.Sum([Объем_тыс_т]), type number}}),

    Мерж = Table.ExpandTableColumn(
        Table.NestedJoin(ГрГод, {"Страна","ГруппаВид","Год"}, ГрПер, {"Страна","ГруппаВид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Мерж, {{"Страна",0},{"ГруппаВид",0},{"Год",0}}),
    СортБуф = Table.Buffer(Сорт),
    МинГодОкна = List.Min(Table.Column(СортБуф, "Год")),

    СПГ = Table.AddColumn(СортБуф, "_ГодПГ", each [Год] - 1, Int64.Type),
    Джн = Table.NestedJoin(СПГ, {"Страна","ГруппаВид","_ГодПГ"}, СортБуф, {"Страна","ГруппаВид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Расш = Table.ExpandTableColumn(Джн, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДин = Table.AddColumn(Расш, "Динамика_%", each
        let
            тек  = if [Объем_Период] = null then 0 else [Объем_Период],
            пред = [_ОбъемПГ]
        in
            if [Год] = МинГодОкна or пред = null or пред = 0 then null
            else (тек - пред) / пред, type number),

    Итог = Table.Sort(
        Table.SelectColumns(СДин, {"Страна","ГруппаВид","Год","Объем_Год","Объем_Период","Динамика_%"}),
        {{"Страна",0},{"ГруппаВид",0},{"Год",0}})
in
    Итог


================================================================================
ОСТАЛЬНЫЕ ИТОГ_* ЗАПРОСЫ -- НЕ ТРЕБУЮТ ПРАВКИ
================================================================================

ИТОГ_Произв_Месяц   -- Pivot, нет YoY самосоединения
ИТОГ_Произв_Производитель -- join с отдельными таблицами
ИТОГ_Имп_Мес        -- Pivot
ИТОГ_Имп_Страна     -- join с отдельными таблицами
ИТОГ_Экс_Мес        -- Pivot
ИТОГ_Экс_Направл    -- join с отдельными таблицами
ИТОГ_Баланс         -- join трёх независимых таблиц
ИТОГ_Отгрузки_Каз   -- простая группировка без YoY
ИТОГ_Цены_КазУзб    -- нет динамики
