//--ИТОГ_Произв_Год
// КАЗ + УЗБ | Страна | Вид | Год | Объем_Год | Объем_Период | Динамика_%
// Все виды (БНД, БНС, БНК, ПБВ и др.) — без фильтра по Вид
// YoY по Объем_Период внутри каждой пары (Страна, Вид)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Фильтр = Table.SelectRows(Производство_Отгрузки_Каз, each
        List.Contains({"Казахстан","Узбекистан"}, [Страна])
        and [Показатель] = "Производство"
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СМесяцем = Table.AddColumn(Фильтр, "НомерМесяца",
        each Number.Mod([КлючМесяца], 100), Int64.Type),

    ДанныеГод = Table.SelectRows(СМесяцем, each
        [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрупГод = Table.Group(ДанныеГод, {"Страна","Вид","Год"},
        {{"Объем_Год", each List.Sum([Значение]), type number}}),

    ДанныеПериод = Table.SelectRows(СМесяцем, each [НомерМесяца] <= МесяцОтч),
    ГрупПериод = Table.Group(ДанныеПериод, {"Страна","Вид","Год"},
        {{"Объем_Период", each List.Sum([Значение]), type number}}),

    Merged = Table.ExpandTableColumn(
        Table.NestedJoin(ГрупГод, {"Страна","Вид","Год"}, ГрупПериод, {"Страна","Вид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Merged, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}}),

    СГодПГ = Table.AddColumn(Сорт, "_ГодПГ", each [Год] - 1, Int64.Type),
    Joined = Table.NestedJoin(СГодПГ, {"Страна","Вид","_ГодПГ"}, Сорт, {"Страна","Вид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Joined, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДинамикой = Table.AddColumn(Expanded, "Динамика_%", each
        if [_ОбъемПГ] = null or [_ОбъемПГ] = 0 then null
        else ([Объем_Период] - [_ОбъемПГ]) / [_ОбъемПГ], type number),

    Итог = Table.SelectColumns(СДинамикой, {"Страна","Вид","Год","Объем_Год","Объем_Период","Динамика_%"})
in
    Итог


//--ИТОГ_Произв_Месяц
// КАЗ + УЗБ | Страна | Вид | НомерМесяца | [год1] | [год2] | [год3]
// Все виды. Прошлые 2 года: 12 мес; текущий год: до МесяцОтч
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Фильтр = Table.SelectRows(Производство_Отгрузки_Каз, each
        List.Contains({"Казахстан","Узбекистан"}, [Страна])
        and [Показатель] = "Производство"),

    СМесяцем = Table.AddColumn(Фильтр, "НомерМесяца",
        each Number.Mod([КлючМесяца], 100), Int64.Type),

    ПоГодам = Table.SelectRows(СМесяцем, each
        [Год] >= ГодОтч - 2
        and [Год] <= ГодОтч
        and not ([Год] = ГодОтч and [НомерМесяца] > МесяцОтч)),

    Сгруппировано = Table.Group(ПоГодам, {"Страна","Вид","НомерМесяца","Год"},
        {{"Объем_тыс_т", each List.Sum([Значение]), type number}}),

    Пивот = Table.Pivot(
        Сгруппировано,
        List.Sort(List.Distinct(Сгруппировано[Год])),
        "Год", "Объем_тыс_т", List.Sum),

    Итог = Table.Sort(Пивот, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"НомерМесяца", Order.Ascending}})
in
    Итог


//--ИТОГ_Произв_Производитель
// КАЗ + УЗБ | Страна | Вид | Производитель | Год | Объем_тыс_т | Доля_%
// Период: мес 1..МесяцОтч для тек. и прош. года
// Доля_% считается внутри (Страна, Вид, Год)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Фильтр = Table.SelectRows(Производство_Отгрузки_Каз, each
        List.Contains({"Казахстан","Узбекистан"}, [Страна])
        and [Показатель] = "Производство"),

    СМесяцем = Table.AddColumn(Фильтр, "НомерМесяца",
        each Number.Mod([КлючМесяца], 100), Int64.Type),

    ДваГода = Table.SelectRows(СМесяцем, each
        ([Год] = ГодОтч or [Год] = ГодОтч - 1)
        and [НомерМесяца] <= МесяцОтч),

    Сгруппировано = Table.Group(ДваГода, {"Страна","Вид","Производитель","Год"},
        {{"Объем_тыс_т", each List.Sum([Значение]), type number}}),

    ИтогВидГод = Table.Group(Сгруппировано, {"Страна","Вид","Год"},
        {{"_Итог", each List.Sum([Объем_тыс_т]), type number}}),

    СИтогом = Table.ExpandTableColumn(
        Table.NestedJoin(Сгруппировано, {"Страна","Вид","Год"}, ИтогВидГод, {"Страна","Вид","Год"}, "_Ит", JoinKind.LeftOuter),
        "_Ит", {"_Итог"}),

    СДолей = Table.AddColumn(СИтогом, "Доля_%",
        each if [_Итог] = 0 then null else [Объем_тыс_т] / [_Итог], type number),

    Итог = Table.Sort(
        Table.RemoveColumns(СДолей, {"_Итог"}),
        {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}, {"Объем_тыс_т", Order.Descending}})
in
    Итог


//--ИТОГ_Импорт_Год
// Все 4 страны | Страна | Вид | Год | Объем_Год | Объем_Период | Динамика_%
// Страна = СтранаНазначения
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаНазначения])
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаНазначения], type text),

    ДанныеГод = Table.SelectRows(СоСтраной, each
        [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрупГод = Table.Group(ДанныеГод, {"Страна","Вид","Год"},
        {{"Объем_Год", each List.Sum([Объем_тыс_т]), type number}}),

    ДанныеПериод = Table.SelectRows(СоСтраной, each [НомерМесяца] <= МесяцОтч),
    ГрупПериод = Table.Group(ДанныеПериод, {"Страна","Вид","Год"},
        {{"Объем_Период", each List.Sum([Объем_тыс_т]), type number}}),

    Merged = Table.ExpandTableColumn(
        Table.NestedJoin(ГрупГод, {"Страна","Вид","Год"}, ГрупПериод, {"Страна","Вид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Merged, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}}),

    СГодПГ = Table.AddColumn(Сорт, "_ГодПГ", each [Год] - 1, Int64.Type),
    Joined = Table.NestedJoin(СГодПГ, {"Страна","Вид","_ГодПГ"}, Сорт, {"Страна","Вид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Joined, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДинамикой = Table.AddColumn(Expanded, "Динамика_%", each
        if [_ОбъемПГ] = null or [_ОбъемПГ] = 0 then null
        else ([Объем_Период] - [_ОбъемПГ]) / [_ОбъемПГ], type number),

    Итог = Table.SelectColumns(СДинамикой, {"Страна","Вид","Год","Объем_Год","Объем_Период","Динамика_%"})
in
    Итог


//--ИТОГ_Импорт_Месяц
// Все 4 страны | Страна | Вид | НомерМесяца | [год1] | [год2] | [год3]
// Страна = СтранаНазначения
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each List.Contains(Страны, [СтранаНазначения])),
    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаНазначения], type text),

    ПоГодам = Table.SelectRows(СоСтраной, each
        [Год] >= ГодОтч - 2
        and [Год] <= ГодОтч
        and not ([Год] = ГодОтч and [НомерМесяца] > МесяцОтч)),

    Сгруппировано = Table.Group(ПоГодам, {"Страна","Вид","НомерМесяца","Год"},
        {{"Объем_тыс_т", each List.Sum([Объем_тыс_т]), type number}}),

    Пивот = Table.Pivot(
        Сгруппировано,
        List.Sort(List.Distinct(Сгруппировано[Год])),
        "Год", "Объем_тыс_т", List.Sum),

    Итог = Table.Sort(Пивот, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"НомерМесяца", Order.Ascending}})
in
    Итог


//--ИТОГ_Импорт_Поставщик
// Все 4 страны | Страна | Вид | Компания | Год | Объем_тыс_т | Доля_%
// Страна = СтранаНазначения. Если не совпадает — замени "Компания" на "Отправитель"
// Доля_% внутри (Страна, Вид, Год)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаНазначения])
        and ([Год] = ГодОтч or [Год] = ГодОтч - 1)
        and [НомерМесяца] <= МесяцОтч),

    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаНазначения], type text),

    Сгруппировано = Table.Group(СоСтраной, {"Страна","Вид","Компания","Год"},
        {{"Объем_тыс_т", each List.Sum([Объем_тыс_т]), type number}}),

    ИтогВидГод = Table.Group(Сгруппировано, {"Страна","Вид","Год"},
        {{"_Итог", each List.Sum([Объем_тыс_т]), type number}}),

    СИтогом = Table.ExpandTableColumn(
        Table.NestedJoin(Сгруппировано, {"Страна","Вид","Год"}, ИтогВидГод, {"Страна","Вид","Год"}, "_Ит", JoinKind.LeftOuter),
        "_Ит", {"_Итог"}),

    СДолей = Table.AddColumn(СИтогом, "Доля_%",
        each if [_Итог] = 0 then null else [Объем_тыс_т] / [_Итог], type number),

    Итог = Table.Sort(
        Table.RemoveColumns(СДолей, {"_Итог"}),
        {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}, {"Объем_тыс_т", Order.Descending}})
in
    Итог


//--ИТОГ_Экспорт_Год
// Все 4 страны | Страна | Вид | Год | Объем_Год | Объем_Период | Динамика_%
// Страна = СтранаОтправления
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаОтправления])
        and [Год] >= ГодОтч - 4 and [Год] <= ГодОтч),

    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаОтправления], type text),

    ДанныеГод = Table.SelectRows(СоСтраной, each
        [Год] < ГодОтч or [НомерМесяца] <= МесяцОтч),
    ГрупГод = Table.Group(ДанныеГод, {"Страна","Вид","Год"},
        {{"Объем_Год", each List.Sum([Объем_тыс_т]), type number}}),

    ДанныеПериод = Table.SelectRows(СоСтраной, each [НомерМесяца] <= МесяцОтч),
    ГрупПериод = Table.Group(ДанныеПериод, {"Страна","Вид","Год"},
        {{"Объем_Период", each List.Sum([Объем_тыс_т]), type number}}),

    Merged = Table.ExpandTableColumn(
        Table.NestedJoin(ГрупГод, {"Страна","Вид","Год"}, ГрупПериод, {"Страна","Вид","Год"}, "_П", JoinKind.LeftOuter),
        "_П", {"Объем_Период"}),
    Сорт = Table.Sort(Merged, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}}),

    СГодПГ = Table.AddColumn(Сорт, "_ГодПГ", each [Год] - 1, Int64.Type),
    Joined = Table.NestedJoin(СГодПГ, {"Страна","Вид","_ГодПГ"}, Сорт, {"Страна","Вид","Год"}, "_ПГ", JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Joined, "_ПГ", {"Объем_Период"}, {"_ОбъемПГ"}),
    СДинамикой = Table.AddColumn(Expanded, "Динамика_%", each
        if [_ОбъемПГ] = null or [_ОбъемПГ] = 0 then null
        else ([Объем_Период] - [_ОбъемПГ]) / [_ОбъемПГ], type number),

    Итог = Table.SelectColumns(СДинамикой, {"Страна","Вид","Год","Объем_Год","Объем_Период","Динамика_%"})
in
    Итог


//--ИТОГ_Экспорт_Месяц
// Все 4 страны | Страна | Вид | НомерМесяца | [год1] | [год2] | [год3]
// Страна = СтранаОтправления
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each List.Contains(Страны, [СтранаОтправления])),
    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаОтправления], type text),

    ПоГодам = Table.SelectRows(СоСтраной, each
        [Год] >= ГодОтч - 2
        and [Год] <= ГодОтч
        and not ([Год] = ГодОтч and [НомерМесяца] > МесяцОтч)),

    Сгруппировано = Table.Group(ПоГодам, {"Страна","Вид","НомерМесяца","Год"},
        {{"Объем_тыс_т", each List.Sum([Объем_тыс_т]), type number}}),

    Пивот = Table.Pivot(
        Сгруппировано,
        List.Sort(List.Distinct(Сгруппировано[Год])),
        "Год", "Объем_тыс_т", List.Sum),

    Итог = Table.Sort(Пивот, {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"НомерМесяца", Order.Ascending}})
in
    Итог


//--ИТОГ_Экспорт_Направления
// Все 4 страны | Страна | Вид | СтранаНазначения | Год | Объем_тыс_т | Доля_%
// Страна = экспортёр (СтранаОтправления). Доля_% внутри (Страна, Вид, Год)
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан","Кыргызстан","Таджикистан"},

    Фильтр = Table.SelectRows(ВЭД, each
        List.Contains(Страны, [СтранаОтправления])
        and ([Год] = ГодОтч or [Год] = ГодОтч - 1)
        and [НомерМесяца] <= МесяцОтч),

    СоСтраной = Table.AddColumn(Фильтр, "Страна", each [СтранаОтправления], type text),

    Сгруппировано = Table.Group(СоСтраной, {"Страна","Вид","СтранаНазначения","Год"},
        {{"Объем_тыс_т", each List.Sum([Объем_тыс_т]), type number}}),

    ИтогВидГод = Table.Group(Сгруппировано, {"Страна","Вид","Год"},
        {{"_Итог", each List.Sum([Объем_тыс_т]), type number}}),

    СИтогом = Table.ExpandTableColumn(
        Table.NestedJoin(Сгруппировано, {"Страна","Вид","Год"}, ИтогВидГод, {"Страна","Вид","Год"}, "_Ит", JoinKind.LeftOuter),
        "_Ит", {"_Итог"}),

    СДолей = Table.AddColumn(СИтогом, "Доля_%",
        each if [_Итог] = 0 then null else [Объем_тыс_т] / [_Итог], type number),

    Итог = Table.Sort(
        Table.RemoveColumns(СДолей, {"_Итог"}),
        {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}, {"Объем_тыс_т", Order.Descending}})
in
    Итог


//--ИТОГ_Баланс_Год
// КАЗ + УЗБ | Страна | Вид | Год | Производство | Импорт | Экспорт | Потребление
// Якорь = все комбинации (Страна, Вид, Год) из трёх источников — ни одна строка не теряется
// Все показатели за период 1..МесяцОтч
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,
    Страны = {"Казахстан","Узбекистан"},
    ДиапГодов = {ГодОтч - 4 .. ГодОтч},

    ПрИсх = Table.AddColumn(
        Table.SelectRows(Производство_Отгрузки_Каз, each
            List.Contains(Страны, [Страна])
            and [Показатель] = "Производство"
            and List.Contains(ДиапГодов, [Год])),
        "НомерМесяца", each Number.Mod([КлючМесяца], 100), Int64.Type),
    Произв = Table.Group(
        Table.SelectRows(ПрИсх, each [НомерМесяца] <= МесяцОтч),
        {"Страна","Вид","Год"}, {{"Производство", each List.Sum([Значение]), type number}}),

    ИмпИсх = Table.AddColumn(
        Table.SelectRows(ВЭД, each
            List.Contains(Страны, [СтранаНазначения])
            and List.Contains(ДиапГодов, [Год])
            and [НомерМесяца] <= МесяцОтч),
        "Страна", each [СтранаНазначения], type text),
    Импорт = Table.Group(ИмпИсх, {"Страна","Вид","Год"},
        {{"Импорт", each List.Sum([Объем_тыс_т]), type number}}),

    ЭкспИсх = Table.AddColumn(
        Table.SelectRows(ВЭД, each
            List.Contains(Страны, [СтранаОтправления])
            and List.Contains(ДиапГодов, [Год])
            and [НомерМесяца] <= МесяцОтч),
        "Страна", each [СтранаОтправления], type text),
    Экспорт = Table.Group(ЭкспИсх, {"Страна","Вид","Год"},
        {{"Экспорт", each List.Sum([Объем_тыс_т]), type number}}),

    ВсеКлючи = Table.Distinct(Table.SelectColumns(
        Table.Combine({
            Table.SelectColumns(Произв,  {"Страна","Вид","Год"}),
            Table.SelectColumns(Импорт,  {"Страна","Вид","Год"}),
            Table.SelectColumns(Экспорт, {"Страна","Вид","Год"})
        }),
        {"Страна","Вид","Год"}
    )),

    Р1 = Table.ExpandTableColumn(
        Table.NestedJoin(ВсеКлючи, {"Страна","Вид","Год"}, Произв,  {"Страна","Вид","Год"}, "_Пр",  JoinKind.LeftOuter),
        "_Пр", {"Производство"}),
    Р2 = Table.ExpandTableColumn(
        Table.NestedJoin(Р1, {"Страна","Вид","Год"}, Импорт,  {"Страна","Вид","Год"}, "_Имп", JoinKind.LeftOuter),
        "_Имп", {"Импорт"}),
    Р3 = Table.ExpandTableColumn(
        Table.NestedJoin(Р2, {"Страна","Вид","Год"}, Экспорт, {"Страна","Вид","Год"}, "_Экс", JoinKind.LeftOuter),
        "_Экс", {"Экспорт"}),

    СПотреблением = Table.AddColumn(Р3, "Потребление", each
        (if [Производство] = null then 0 else [Производство])
        + (if [Импорт] = null then 0 else [Импорт])
        - (if [Экспорт] = null then 0 else [Экспорт]),
        type number),

    Итог = Table.Sort(СПотреблением,
        {{"Страна", Order.Ascending}, {"Вид", Order.Ascending}, {"Год", Order.Ascending}})
in
    Итог


//--ИТОГ_Цены
// КАЗ + УЗБ | Страна | НомерМесяца | [год1] | [год2] | [год3]
// Цены не разбиты по Вид в источнике — без колонки Вид
// Прошлые 2 года: 12 мес; текущий год: до МесяцОтч
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Фильтр = Table.SelectRows(Цены_Каз_Узб, each [ТипЦены] = "Средняя"),

    ПоГодам = Table.SelectRows(Фильтр, each
        [Год] >= ГодОтч - 2
        and [Год] <= ГодОтч
        and not ([Год] = ГодОтч and [НомерМесяца] > МесяцОтч)),

    Выбор = Table.SelectColumns(ПоГодам, {"Страна","НомерМесяца","Год","Цена"}),

    Пивот = Table.Pivot(
        Выбор,
        List.Sort(List.Distinct(Выбор[Год])),
        "Год", "Цена", List.Average),

    Итог = Table.Sort(Пивот, {{"Страна", Order.Ascending}, {"НомерМесяца", Order.Ascending}})
in
    Итог


//--ИТОГ_Цены_РФ
// Цены РФ как ориентир | НомерМесяца | [год1] | [год2] | [год3]
// Без Страна и Вид — единый рыночный ориентир
// Прошлые 2 года: 12 мес; текущий год: до МесяцОтч
let
    ГодОтч = Date.Year(ДатаОтчета),
    МесяцОтч = МесяцОтчета,

    Фильтр = Table.SelectRows(Цены_РФ, each [ТипЦены] = "Средняя"),

    ПоГодам = Table.SelectRows(Фильтр, each
        [Год] >= ГодОтч - 2
        and [Год] <= ГодОтч
        and not ([Год] = ГодОтч and [НомерМесяца] > МесяцОтч)),

    Пивот = Table.Pivot(
        ПоГодам,
        List.Sort(List.Distinct(ПоГодам[Год])),
        "Год", "Значение", List.Average),

    Итог = Table.Sort(Пивот, {{"НомерМесяца", Order.Ascending}})
in
    Итог
