//--Производство_Каз
let
    ПутьФайла = Функция_параметр("Путь_Производство_Каз"),
    ИмяТаблицы = Функция_параметр("Таблица_Производство_Каз"),
    Книга = Excel.Workbook(File.Contents(ПутьФайла), null, true),
    Данные = Книга{[Item=ИмяТаблицы, Kind="Table"]}[Data],
    Типы = Table.TransformColumnTypes(
        Данные,
        {
            {"Год", Int64.Type},
            {"Дата", type date},
            {"Кластер", type text},
            {"Регион", type text},
            {"Вид", type text},
            {"Компания", type text},
            {"Производитель", type text},
            {"Объем производства", type number},
            {"ОбъемПроизводство, тыс.т", type number}
        },
        "ru-RU"
    )
in
    Типы


//--Факт_Производство_Каз
let
    Источник = Производство_Каз,

    ДобавитьСтрану = Table.AddColumn(Источник, "Страна", each "Казахстан", type text),
    ДобавитьПоказатель = Table.AddColumn(ДобавитьСтрану, "Показатель", each "Производство", type text),

    ВыборСтолбцов = Table.SelectColumns(
        ДобавитьПоказатель,
        {
            "Страна",
            "Показатель",
            "Дата",
            "Год",
            "Вид",
            "Компания",
            "Производитель",
            "Кластер",
            "Регион",
            "ОбъемПроизводство, тыс.т"
        }
    ),

    Переименование = Table.RenameColumns(
        ВыборСтолбцов,
        {{"ОбъемПроизводство, тыс.т", "Значение"}}
    ),

    ЗаменаNull = Table.ReplaceValue(Переименование, null, 0, Replacer.ReplaceValue, {"Значение"}),

    ДобавитьЕд = Table.AddColumn(ЗаменаNull, "ЕдИзм", each "тыс.т", type text),

    Итог = Table.ReorderColumns(
        ДобавитьЕд,
        {"Страна","Показатель","Дата","Год","Вид","Компания","Производитель","Кластер","Регион","Значение","ЕдИзм"}
    )
in
    Итог


//--Производство_Узб
let
    ПутьФайла = Функция_параметр("Путь_Производство_Узб"),
    ИмяТаблицы = Функция_параметр("Таблица_Производство_Узб"),
    Книга = Excel.Workbook(File.Contents(ПутьФайла), null, true),
    Данные = Книга{[Item=ИмяТаблицы, Kind="Table"]}[Data],
    Типы = Table.TransformColumnTypes(
        Данные,
        {
            {"Год", Int64.Type},
            {"Дата", type date},
            {"Кластер", type text},
            {"Регион", type text},
            {"Вид", type text},
            {"Компания", type text},
            {"Производитель", type text},
            {"Объем производства", type number},
            {"Значение", type number}
        },
        "ru-RU"
    ),
    #"Удаленные столбцы" = Table.RemoveColumns(Типы,{"Объем производства"})
in
    #"Удаленные столбцы"


//--Факт_Отгрузки_Каз
let
    Источник = Отгрузки_Каз,
    ДобавитьСтрану = Table.AddColumn(Источник, "Страна", each "Казахстан", type text),
    ДобавитьПоказатель = Table.AddColumn(ДобавитьСтрану, "Показатель", each "Отгрузки", type text),

    Выбор = Table.SelectColumns(
        ДобавитьПоказатель,
        {"Страна","Показатель","Дата","Год","Кластер","Регион","Производитель","Объем_тыс.т","Вид"}
    ),

    Переименование = Table.RenameColumns(Выбор, {{"Объем_тыс.т","Значение"}}),

    ДобавитьКомпания = Table.AddColumn(Переименование, "Компания", each null, type text),
    ДобавитьЕд = Table.AddColumn(ДобавитьКомпания, "ЕдИзм", each "тыс.т", type text),

    Итог = Table.ReorderColumns(
        ДобавитьЕд,
        {"Страна","Показатель","Дата","Год","Вид","Компания","Производитель","Кластер","Регион","Значение","ЕдИзм"}
    )
in
    Итог



//-- Производство_Отгрузки_Каз
let
    Источник = Table.Combine({Факт_Отгрузки_Каз, Факт_Производство_Каз}),
    #"Добавленный запрос" = Table.Combine({Источник, Производство_Узб}),
    ДобавитьКлючМесяца = Table.AddColumn(
    #"Добавленный запрос",
    "КлючМесяца",
    each Date.Year([Дата]) * 100 + Date.Month([Дата]),
    Int64.Type
)
in
    ДобавитьКлючМесяца
